#!/usr/bin/env python3

import configparser
import argparse
import shutil
import sys
import re

class PacConfParser(configparser.ConfigParser):
    def optionxform(self, option):
        return option

def query_yes_no(question, default="yes"):
    """Ask a yes/no question and returns the user's answer.

    "question" is a string that is presented to the user.
    "default" is the presumed answer if the user just hits <Enter>. It must be "yes" (the default), "no" or None (meaning an answer is required of the user).

    The return value is a boolean.
    """

    valid = { "yes": True, "y": True, "ye": True, "no": False, "n": False }
    if default is None:
        prompt = " [y/n] "
    elif default == "yes":
        prompt = " [Y/n] "
    elif default == "no":
        prompt = " [y/N] "
    else:
        raise ValueError("invalid default answer: '%s'" % default)

    while True:
        sys.stdout.write(question + prompt)
        choice = input().lower()
        if default is not None and choice == '':
            return valid[default]
        elif choice in valid:
            return valid[choice]
        else:
            sys.stdout.write("Please respond with 'yes' or 'no' (or 'y' or 'n').\n")

def get_arg_parser():
    parser = argparse.ArgumentParser(description = 'Manage pacman repositories.')
    group = parser.add_mutually_exclusive_group(required = True)
    group.add_argument('-I', '--install', action = 'store_true', help = 'install into pacman.conf')
    group.add_argument('-A', '--add', action = 'store_true', help = 'add the repository NAME with URL')
    group.add_argument('-R', '--remove', action = 'store_true', help = 'remove the repository NAME')
    parser.add_argument('--name', help = 'the repository identifier')
    parser.add_argument('--url', help = 'the repository server')
    return parser

class PacRepos:
    PACMAN_FILE = '/etc/pacman.conf'
    CONFIG_FILE = '/etc/pacrepos.conf'

    RE_INSTALL_CHECK = re.compile(' ^ \\s* Include \\s* = \\s* {0} \\s* ( [#] .* )? $ '.format(re.escape(CONFIG_FILE)), re.VERBOSE | re.MULTILINE | re.IGNORECASE)

    def _read_config(self):
        config = PacConfParser()
        config.read(self.CONFIG_FILE)
        return config

    def _write_config(self, config):
        with open(self.CONFIG_FILE, 'w') as file:
            file.write('# Generated by the pacrepos tool\n')
            file.write('\n')
            config.write(file)

    def is_installed(self):
        with open(self.PACMAN_FILE, 'r') as file:
            return bool(self.RE_INSTALL_CHECK.search(file.read()))

    def install(self):
        if self.is_installed():
            raise Exception('Already installed.')

        print("Installing packages from unofficial repositories is unsupported and discouraged and could partially or completely break your system. You probably won't get much technical support if that happens, so do it only if you know how to repair your system.")
        if not query_yes_no("Do you want to continue?", default = "no"):
            return

        shutil.copyfile(self.PACMAN_FILE, '{0}.old'.format(self.PACMAN_FILE))
        with open(self.PACMAN_FILE, 'a') as file:
            file.write('\n')
            file.write('Include = {0}\n'.format(self.CONFIG_FILE))
        with open(self.CONFIG_FILE, 'a+'):
            pass # just create the file

    def add_repo(self, name, url):
        config = self._read_config()
        if name in config:
            raise Exception("Repository '{0}' is already present.".format(name))
        config[name] = { 'Server': url, 'SigLevel': 'Optional' }
        self._write_config(config)

    def remove_repo(self, name):
        config = self._read_config()
        if name not in config:
            raise Exception("Repository '{0}' is not present.".format(name))
        del config[name]
        self._write_config(config)

args = get_arg_parser().parse_args()
repos = PacRepos()

if args.install:
    repos.install()
else:
    if not args.name:
        raise Exception('Name is required when adding or removing a repository.')

    if not repos.is_installed():
        print("Don't forget to run '{0} --install'.".format(sys.argv[0]))

    if args.add:
        if not args.url:
            raise Exception('URL is required when adding a repository.')
        repos.add_repo(args.name, args.url)
    elif args.remove:
        repos.remove_repo(args.name)
